spring.datasource.url=jdbc:postgresql://ep-broad-paper-b5uibzgf-pooler.c-7.us-east-2.aws.neon.tech/neondb?sslmode=require&stringtype=unspecified
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=neondb_owner
spring.datasource.password=npg_tCFbJ3s6OvAZ

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=600000
#spring.datasource.hikari.keepalive-time=30000
#spring.datasource.hikari.connection-test-query=SELECT 1
#spring.datasource.hikari.validation-timeout=3000
